### ISSUE TITLE
Downloading chromedriver breaks for certain versions

### ISSUE THREAD

**Issue by ViktoriiaKovalova** [GoogleChromeLabs/chromeos_smart_card_connector#1009]
Example: https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/6097245953/job/16544492257

Currently we are downloading chromedriver with the same version as Chrome currently installed on device. However, sometimes it breaks (see example).

It's probably better to use some versions provided by these [endpoints](https://github.com/GoogleChromeLabs/chrome-for-testing#json-api-endpoints) for chromedriver.
Maybe this one: `https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE`

**Comment by emaxx-google** [comment]
Argh - they promised that there's always an exactly matching Chromedriver build...

> Starting with M115, across all release channels (Stable, Beta, Dev, Canary), every Chrome release that gets pushed to users automatically gets a correspondingly-versioned ChromeDriver release, [available for download via Chrome for Testing infrastructure](https://googlechromelabs.github.io/chrome-for-testing/).

https://groups.google.com/g/chromedriver-users/c/clpipqvOGjE

Which, obviously, doesn't hold as what we see on Github Actions bots is Chrome `116.0.5845.140` and 404 for https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.140/linux64/chromedriver-linux64.zip . I've double-checked https://googlechromelabs.github.io/chrome-for-testing/known-good-versions.json and it doesn't contain anything for this version of Chrome either.

**Comment by emaxx-google** [comment]
I saw your PR (thanks for taking a stab at it!). I think an alternative direction would be trying to fetch the closest version of Chromedriver, given the locally installed Chrome version.

This would rely on the assumption that they do at least one proper Chromedriver release for every Chrome milestone. Which is weaker than what they originally promised and sounds reasonable, but who knows...
