### ISSUE TITLE
CI breaks for non-emscripten/pnacl toolchains

### ISSUE THREAD

**Issue by ViktoriiaKovalova** [GoogleChromeLabs/chromeos_smart_card_connector#1014]
CI breaks >50% of the time for asan-testing/collect-coverage/lint-js with the following error:
```
Post job cleanup.
Post job cleanup.
Error: Cache folder path is retrieved for pip but doesn't exist on disk: /home/runner/.cache/pip
```
Example:
https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/6111626282/job/16587278119?pr=1013

This seems to happen only for those jobs, because they don't use python after installation.

Related issue in setup-python repo:
https://github.com/actions/setup-python/issues/436

I tried checking if it still happens with setup-python@v4 and it still broke ([example link](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/actions/runs/6111626282/job/16587278119?pr=1013)).

Probably we can disable setup-python for those toolchains as a workaround.

**Comment by emaxx-google** [comment]
Thanks for filing and for the initial investigation. Maybe we can apply this workaround: https://github.com/actions/setup-python/issues/436#issuecomment-1542331828 ?
