### ISSUE TITLE
How to add extension to allowlist

### ISSUE THREAD

**Issue by alizarei95** [GoogleChromeLabs/chromeos_smart_card_connector#1112]
Hi there,
I read [this](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/blob/main/docs/connector-app-api.md) topic and found out that there is whitelist to omit first-time permission. How is it possible to add our extension to this list?

**Comment by emaxx-google** [comment]
Hi, you can create a Pull Request that adds your extension to the allowlist: https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/blob/main/third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json .

We'll review it internally.
