### ISSUE TITLE
Still getting permission despite adding admin policy

### ISSUE THREAD

**Issue by alizarei95** [GoogleChromeLabs/chromeos_smart_card_connector#1113]
Hi there,
I added below rule in admin console and saved changes but it still shows permission dialog for first time usage
{
  "force_allowed_client_app_ids": {
    "Value": ["naabfciimcjlmnohcligmgihhpihloah"]
  }
}

**Comment by emaxx-google** [comment]
Hello, could you please share the policy dump from the Chromebook? It can be obtained at `chrome://policy`. Feel free to send it to cros-smartcard-support@google.com in case you're uncomfortable with attaching it here publicly.

**Comment by alizarei95** [comment]
I've sent an email with exported policy, can you please check it?
@emaxx-google

**Comment by emaxx-google** [comment]
Closing this as obsolete (for posterity, this wasn't well understood, but presumably there was an issue with delivering policies to the devices).
