### ISSUE TITLE
Clean up Native Client specific code

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#1211]
After we finally switch to WebAssembly everywhere, we should delete all legacy NaCl-related code.

**Comment by Test18415** [comment]
We use the https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/blob/main/third_party/pcsc-lite/naclport/js_client/src/api.js in our app, since it is in the naclport folder, will this still work?

**Comment by emaxx-google** [comment]
> We use the https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/blob/main/third_party/pcsc-lite/naclport/js_client/src/api.js in our app, since it is in the naclport folder, will this still work?

Yes - I'm going to rename the folder to avoid confusion.

**Comment by emaxx-google** [comment]
As a status update, we're doing with deleting the "really" NaCl-specific code: #1206, #1207, #1208, #1209, #1210, #1216.

**Comment by emaxx-google** [comment]
Copying the description from #1220 here for visibility: the `third_party/pcsc-lite/naclport/server_clients_management/src/known_client_apps.json` file has been moved to `smart_card_connector_app/src/trusted_clients.json`. It's a cosmetic change.

**Comment by emaxx-google** [comment]
The second train of PRs went in, renaming the files/dirs that are still used post-NaCl: #1220, #1224, #1225.

**Comment by emaxx-google** [comment]
The only remaining thing is to modernize the C++ code in places where we were previously held back by NaCl toolchain level of support (which was an incomplete C++11).

**Comment by emaxx-google** [comment]
The cleanup finished with these PRs: #1213, #1227, #1228.
