### ISSUE TITLE
Stop building our libraries separately

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#133]
Currently, the build process is organized in a way that each sub-library (like //common/cpp) is built separately and then has its .lib+.h files installed into a common place (in the NaCl environment). The .lib files are then used when linking the resulting executable.

The original motivation behind this approach is pretty much described in issue #132; additionally, it allows to avoid recompiling a library multiple times for different executables and to test it without compiling the rest of the code. However, similar to that issue, the benefits of that approach don't outweigh the complexity and the fragility caused by it.

Therefore the suggestion is to get rid of that model and separate .lib files, and instead directly compile every library's source file as part of the resulting target.

**Comment by mdfarvezbuiyan** [comment]
hello

**Comment by emaxx-google** [comment]
I'm not sure anymore it'd be a good idea. This would be non-conventional (given that the code is actually consisting of several self-contained blocks that come from different upstreams and are compiled with different flags). Implementation-wise it'd also be weird.
