### ISSUE TITLE
SCardGetStatusChange returns wrong data in message JSON

### ISSUE THREAD

**Issue by vscfreire** [GoogleChromeLabs/chromeos_smart_card_connector#393]
Since version 1.3.5.0 (the bug does not occur in 1.3.3.0) we are getting a wrong behavior on the JSON received from the Smart Card Connector, regarding the response of a `SCardGetStatusChange` request.

The `atr` attribute should be a list, either empty (`[]`) when no card is inserted, or a list with the bytes from the inserted card's ATR. This was the case until 1.3.3.0, but since 1.3.5.0, the `atr` attribute is always an empty object (`{}`), which causes problems from that point on. 

We send the connector a `SCardGetStatusChange` request:

```
{
    "function_name": "SCardGetStatusChange",
    "arguments": [
        175319793,
        0,
        [
            {
                "reader_name": "Gemalto PC Twin Reader 00 00",
                "current_state": 0
            }
        ]
    ]
}
```
...and get back this response:
```
{
    "type": "pcsc_lite_function_call::response",
    "data": {
        "request_id": 2,
        "payload": [
            0,
            [
                {
                    "atr": {},
                    "current_state": 0,
                    "event_state": 34,
                    "reader_name": "Gemalto PC Twin Reader 00 00"
                }
            ]
        ]
    }
}
```
Notice the empty object (`{}`) returned as the `atr` attribute.
The log file contains the correct reply from the smart card, showing that the problem is after that point, in the data which is sent as a Google Chrome message to the extension:
```
[210918 20:08:54.61] [NaclModule] [INFO] [PC/SC from "ckhdehpbimdohoflpgoohhkffeipofmp" (id 1)] SCardGetStatusChange#8(hContext=0x0A732AF1, dwTimeout=0, rgReaderStates=0xFEB368B0[{szReader="Gemalto PC Twin Reader 00 00", pvUserData=NULL, dwCurrentState=SCARD_STATE_UNAWARE}]): called...

[210918 20:08:54.61] [NaclModule] [INFO] [PC/SC from "ckhdehpbimdohoflpgoohhkffeipofmp" (id 1)] SCardGetStatusChange#8: returning 0x00000000 ["Command successful."], rgReaderStates=0xFEB368B0[{szReader="Gemalto PC Twin Reader 00 00", pvUserData=NULL, dwCurrentState=SCARD_STATE_UNAWARE, dwEventState=SCARD_STATE_CHANGED|SCARD_STATE_PRESENT, cbAtr=25, rgbAtr=<0x3B 0xFF 0x96 0x00 0x00 0x81 0x31 0xFE 0x43 0x80 0x31 0x80 0x65 0xB0 0x85 0x04 0x01 0x20 0x12 0x0F 0xFF 0x82 0x90 0x00 0xD0>}]
```
But the `rbgAtr` values are not received in the message from the Smart Card Connector.
The correct response should be (taken from 1.3.3.0):
```
{
    "type": "pcsc_lite_function_call::response",
    "data": {
        "request_id": 1,
        "payload": [
            0,
            [
                {
                    "atr": [
                        59,
                        255,
                        150,
                        0,
                        0,
                        129,
                        49,
                        254,
                        67,
                        128,
                        49,
                        128,
                        101,
                        176,
                        133,
                        4,
                        1,
                        32,
                        18,
                        15,
                        255,
                        130,
                        144,
                        0,
                        208
                    ],
                    "current_state": 0,
                    "event_state": 196642,
                    "reader_name": "Gemalto PC Twin Reader 00 00"
                }
            ]
        ]
    }
}
```
Or, with no smart card inserted:
```
{
    "type": "pcsc_lite_function_call::response",
    "data": {
        "request_id": 1,
        "payload": [
            0,
            [
                {
                    "atr": [],
                    "current_state": 0,
                    "event_state": 131090,
                    "reader_name": "Gemalto PC Twin Reader 00 00"
                }
            ]
        ]
    }
}
```
Notice the empty list (`[]`) and not empty object in the `atr`attribute.
I'm including a text file with all `SCardEstablishContext`, `SCardListReaders` and `SCardGetStatusChange`, for all cases (version 1.3.3.0, with or without card -- working OK, and version 1.3.5.0, with or without card -- not working OK), including JSON requests and responses, as well as corresponding log messages from the Smart Card Connector.

Thanks

[chromeos-smartcardconnector-bug.txt](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/files/7190546/chromeos-smartcardconnector-bug.txt)
!

**Comment by emaxx-google** [comment]
Hello, thank you for the report!
I'll look into this later, although the first thought is that it might be related to ArrayBuffer-related changes (#226 et al.).

**Comment by dsijms** [comment]
Hello all,


we have around 5.000 chromeOS devices used in a network of twenty hospitals and clinics, that depend on this connector to identify doctors and prescribe medication.

Please kindly fix this as soon as possible as it is now a critical component of our solution.

Best Regards,
Bruno Silva

**Comment by emaxx-google** [comment]
I'm actually unable to reproduce the issue so far.

My attempt was: to open DevTools on a client application (CSSI haeblkpifdemlfnkogkipmghfcbonief, but it shouldn't matter) and set a breakpoint to `GoogleSmartCard.PortMessageChannel.prototype.messageEventHandler_()`. After skipping several uninteresting incoming messages, I observed a response to SCardGetStatusChange, which seems correct:
```
> JSON.stringify(a)
'{"type":"pcsc_lite_function_call::response","data":{"request_id":8,"payload":[0,[{"atr":[59,219,150,0,128,177,254,69,31,131,0,49,192,100,199,252,16,0,1,144,0,116],"current_state":0,"event_state":34,"reader_name":"OMNIKEY AG CardMan 3121 00 00"}]]}}'
```

So I haven't observed the problem you've reported - an empty object (`{}`) in the ATR field. How did you collect these logs in your report? Could it be that you collected them by calling `JSON.stringify()` in the Smart Card Connector's background page? That would explain it, since in the Smart Card Connector all byte fields, including ATR, are represented as ArrayBuffers, and JSON serialization misinterprets them as empty objects. But that wouldn't reflect a real issue per se, since #226 made sure we don't send ArrayBuffers in cross-extension messages.

**Comment by emaxx-google** [comment]
I did another test by adding a SCardGetStatusChange() call into our Example Extension (#394). Still no luck in reproing the issue:
```
Received reader card insertion event: [{"atr":[59,219,150,0,128,177,254,69,31,131,0,49,192,100,199,252,16,0,1,144,0,116],"current_state":16,"event_state":34,"reader_name":"OMNIKEY AG CardMan 3121 00 00"}]
```

**Comment by vscfreire** [comment]
OK, I think I see where the problem is.

You are not able to replicate the problem because your Example Extension does not use cross-extension messages. That is indeed the problem, because the Smart Card connector is in fact sending `ArrayBuffer` in those messages in 1.3.5.0, whereas in 1.3.3.0 was using regular arrays (which are serializable with `JSON.stringify()`, while `ArrayBuffer` are not).

We've placed a `console.log()` before the `chrome.runtime.sendMessage()` call in `SingleMessageBasedChannel.prototype.send()` on the `single-message-based-channel.js` file -- [here](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/blob/36491f4b6a5209a7795fb1a749fb42df40242503/common/js/src/messaging/single-message-based-channel.js#L113) -- (we've actually edited the compiled `background.js` file in the 1.3.5.0 CRX file from the store to make sure), and it is sending an `ArrayBuffer` instead of an `Array`.

### 1.3.3.0

![sendMessage-1 3 3 0](https://user-images.githubusercontent.com/35369554/133944792-c39ff4cd-dc69-407b-9376-92e86f2dc68b.png)

### 1.3.5.0

![sendMessage-1 3 5 0](https://user-images.githubusercontent.com/35369554/133944798-e3a06e2a-eae6-46ba-935d-64461833680e.png)

Of course, as you say, the extension receives the message attribute after being serialized/unserialized with JSON, resulting in a `{}`.

**Comment by vscfreire** [comment]
We've also tried another thing. Before the `chrome.runtime.sendMessage(this.extensionId, message)` call described in the previous commend, we've added:
```
message = GoogleSmartCard.ContainerHelpers.substituteArrayBuffersRecursively(message);
```
And everything works correctly.

Apparently this function (implemented in #226) is not being called?

Thanks!

**Comment by emaxx-google** [comment]
You're totally right, we forgot about calling it in the single-message-based implementation (which also reveals our insufficient testing in that area). I'm working on a pull request now.

@vscfreire What's the client application you're working on? (WebStore gives 404 for the "ckhdehpbimdohoflpgoohhkffeipofmp" ID that's quoted in the logs above.)
I'm asking since we may need to tell the QA team to test this scenario as well, if it's reasonable to set it up on our side.

**Comment by vscfreire** [comment]
Just tested the newly released 1.3.6.0 version, and it works great.

Any idea on the timeframe until it gets to the store?

**Comment by emaxx-google** [comment]
Thank you. We've published it on WebStore, so it shouldn't take longer than 24h (in practice it's often faster, although without guarantees).

**Comment by emaxx-google** [comment]
Actually in my region 1.3.6.0 already surfaced by WebStore, so it went faster than expected. But I can't speak for customer's deployments, as WebStore sharding rules can be complex.

P.S. Rebooting affected machines might help to get the update faster, since we don't allow smart card app updates in-session (in order to not interrupt any operation).
