### ISSUE TITLE
Permission from third party to access Smart Card Connector not prompted  

### ISSUE THREAD

**Issue by ayaNader** [GoogleChromeLabs/chromeos_smart_card_connector#440]
When launching the third party app/extension (such as CSSI or CACKey), a permission prompt must be shown to ask the user whether or not they allow the the third party to access the Smart Card Connector. This happens in the extension mode but in the app mode the permission prompt isn't shown and the third party automatically has access to the Smart Card Connector App.
This issue occurred after the changes made in #423.

**Comment by TJ4Urservices** [comment]
Yes wow this happens every time i do multiple password change like i would go sign in to my Gmail account and find out the password was changed. Then just literally two seconds after I change the password he would change it and then I would change it again. This would be consistently on all the emails going on for hours upon hours emotionally and physically just trying to be faster than him trying.
