### ISSUE TITLE
Add tooltips for the reader status indicators

### ISSUE THREAD

**Issue by emaxx-google** [GoogleChromeLabs/chromeos_smart_card_connector#48]
The meaning of the indicator color (which can be red, yellow and green) is not absolutely clear from the user perspective.

**Comment by emaxx-google** [comment]
BTW, the color-based approach is also not good from the accessibility perspective: users might have troubles with distinguishing the colors.

**Comment by ayaNader** [comment]
So maybe writing the status next to the reader name (Success/Failure/Warning)?

**Comment by emaxx-google** [comment]
Let's probably start from the tooltips for the icons as a small improvement. This icon is a non-crucial piece of the UI, but having it clarified in form of tooltips would make it clearer for the curious users.

As for displaying the status clear-text - we'd have to make sure we're not making the UI overcomplicated. Some thoughts:
* When everything is alright (which is 99% of all scenarios), it's probably better to just show the reader name, without any additional labels.
* Note that in the case of failure, we already display the word "error" and (together with the error code).
* So the only remaining state is the "yellow" intermediate state; but that one is usually displayed only for a fraction of a second - so again probably better to avoid any additional labels, since they'll just cause flickering.
