### ISSUE TITLE
Migrate to python3

### ISSUE THREAD

**Issue by Fabian-Sommer** [GoogleChromeLabs/chromeos_smart_card_connector#527]
We currently need python2 to build the smart card connector. Since python2 will go away at some point, we need to migrate to python3.

**Comment by emaxx-google** [comment]
This is mostly done, except in the code that calls NaCl SDK. I don't think we should invest into migrating the latter, since it'll be lots of efforts into a legacy toolchain that'll be removed in mid-term future. Hence closing this as fixed.
