### ISSUE TITLE
Policy handling is not backwards compatible

### ISSUE THREAD

**Issue by alex292** [GoogleChromeLabs/chromeos_smart_card_connector#540]
We used to have the following policy value for the smart card app:
```
{
   "force_allowed_client_app_ids":{
      "Value":[
         "haiffjcadagjlijoggckpgfnoeiflnem",
         "lbfgjakkeeccemhonnolnmglmfmccaag"
      ]
   }
}
```
i.e. a list of extension IDs.

With the latest dogfood release (version 1.3.7.1), these values no longer work. We are unexcpectedly seeing the "Don't grant access to unknown applications unless you know what you are doing!" dialog.

The logs indicate that it is looking for "chrome-extension://<<<EXTENSION_ID>>>" instead of "<<<EXTENSION_ID>>>" in the policy values.
![Screenshot 2022-05-07 at 00 58 51](https://user-images.githubusercontent.com/3793004/167226737-711b4157-871d-4020-a057-cc451056e34a.png)

Updating the extension policy to the following:
```
{
   "force_allowed_client_app_ids":{
      "Value":[
         "chrome-extension://haiffjcadagjlijoggckpgfnoeiflnem",
         "chrome-extension://lbfgjakkeeccemhonnolnmglmfmccaag"
      ]
   }
}
```
solves the issue.

The old values should likely still work in order to be backwards-compatible.

**Comment by emaxx-google** [comment]
Should be fixed in >=1.3.7.2.
Thanks again for reporting this.
