### ISSUE TITLE
unable to recognize card reader

### ISSUE THREAD

**Issue by esegara** [GoogleChromeLabs/chromeos_smart_card_connector#63]
the application is unable to recognize card reader pcProx by RFIDeas device id c27:3bfa. 

The device is recognized by the ChromeOS but not the application. we have used other commercial connectors like QwickACCESS and they recognize the reader but not the smart card connector app. We would like to use an opensource version rather than a commercial one.

**Comment by emaxx-google** [comment]
Unfortunately, this reader is not supported by the open-source driver that we use - the CCID free software. See https://ccid.apdu.fr/ccid/section.html for the list of supported hardware.

In case you have enough interest and the device you mention is compliant to the CCID specification, you may want to reach out to maintainers of the CCID project to include the support of this reader: https://ccid.apdu.fr/#CCID_compliant
