### ISSUE TITLE
Support for devices 096e:0854 and 1ea8:fc25

### ISSUE THREAD

**Issue by robertswiecki** [GoogleChromeLabs/chromeos_smart_card_connector#644]
Hi,

I have two FIDO2 keys, both from Token2 (https://token2.swiss) but based on Feitian (096e:0854) and Excelsecu (1ea8:fc25).

They work nicely with ecdsa-sk ssh keys under regular Linux, but I'd like to use them with ChromeOS. Is it as simple as adding those identifiers to the manifest and to other config files, or maybe some additional testing will be needed?

**Comment by emaxx-google** [comment]
Hello, the devices aren't present in the upstream CCID driver's matrix (https://ccid.apdu.fr/ccid/section.html), so I can't say if they are supported or not.

The CCID project describes how to report new devices to be added into the config: https://ccid.apdu.fr/#CCID_compliant. Would it be possible for you to follow these steps? Thanks.

**Comment by robertswiecki** [comment]
Hm.. if this software supports only CCID devices, then the both devices mentioned above are pure FIDO2/U2F devices, using the HID class, so probably not something supported by the software. I'll close it then.

**Comment by emaxx-google** [comment]
I see, yes, I should've started from checking that. Correct - Smart Card Connector only works with CCID devices at the moment.

As for FIDO2/U2F tokens you mentioned - I would recommend you filing a bug to Chromium bug tracker (crbug.com).

**Comment by robertswiecki** [comment]
Yup, thanks for the pointer - I think they're discussing it in the context of Crostini VMs, and I'm more interested in the Chrome OS Secure Shell extension. The Yubikey's CCID interface works well with the connector BTW (both in the Chrome OS Secure Shell and in Crostini - here natively, as a USB passthrogh).

PS: Given that the FIDO2 application tokens usage is probably growing, b/c more and more tokens support fido2 now, maybe that's something you'd consider supporting in this app as an additional protocol? Unfortunately the Chrome OS Secure Shell applet doesn't support FIDO2.

**Comment by emaxx-google** [comment]
> Yup, thanks for the pointer - I think they're discussing it in the context of Crostini VMs, and I'm more interested in the Chrome OS Secure Shell extension. The Yubikey's CCID interface works well with the connector BTW (both in the Chrome OS Secure Shell and in Crostini - here natively, as a USB passthrogh).
> 
> PS: Given that the FIDO2 application tokens usage is probably growing, b/c more and more tokens support fido2 now (though w/o CCID), maybe that's something you'd consider supporting in this app as an additional protocol? Unfortunately the Chrome OS Secure Shell applet doesn't support FIDO2.

Should it be a feature request for the Secure Shell app? I'm not sure the Smart Card Connector should be the right component, given that IIUC Chrome provides native FIDO2 support for websites.
