### ISSUE TITLE
A reader is not removed when it is physically disconnected

### ISSUE THREAD

**Issue by xtralogic** [GoogleChromeLabs/chromeos_smart_card_connector#67]
When a reader is disconnected it is not removed from the UI and also continues to be reported to the client apps. When the reader reconnected, it does not work.
This affects only Beta and Dev Chrome OS channels, the Stable channel works fine.

Steps to reproduce        
-Install and launch the Smart Card Conenctor app.
-Connect a reader to a USB port, it is recognized and shown in the app UI correctly. Insert/remove a smart card, the reader icon changes accordingly.
-Disconnect the reader, it remains shown in the UI and continues to be reported to the client apps.
-Connect the reader back, the reader is still shown, but the icon does not change when a smart card inserted/removed.
-The only way to clear the condition is to re-install the Smart Card Connector app or reboot the Chromebook.
-This was reproduced with two different Smart card readers.
-If a second smart card reader is connected after the first one disconnected, the second one is is not shown as if the app just hung.

Environment details:
Chromebook Pixel, model C0A.
The Smart Card Connector app (id "khpfeaanjngmcnplbdlpegiifgpfgdco", version 1.2.22.0)
Stable channel: Chrome OS 74.0.3729.125
Beta channel: Chrome OS 75.0.3770.24
Dev channel: Chrome OS 75.0.3770.19
USB Smart card readers tested:
"Gemalto PC Twin Reader" "vendorId": 0x000008E6, "productId": 0x00003437
"Alcor Micro AU9560" "vendorId": 0x0000058F, "productId": 0x00009540

[smart-card-connector-log-bad-dev-channel-chrome-75.0.3770.19.txt](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/files/3196406/smart-card-connector-log-bad-dev-channel-chrome-75.0.3770.19.txt)
[smart-card-connector-log-good-stable-channel-chrome-74.0.3279.125.txt](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/files/3196407/smart-card-connector-log-good-stable-channel-chrome-74.0.3279.125.txt)
[smart-card-connector-log-bad-beta-channel-chrome-75.0.3770.24.txt](https://github.com/GoogleChromeLabs/chromeos_smart_card_connector/files/3196408/smart-card-connector-log-bad-beta-channel-chrome-75.0.3770.24.txt)

**Comment by FabianHenneke** [comment]
I am experiencing the same issue on an Acer Chromebook 14 (model CB3-431), which is also on the Beta channel with Chrome OS 75.0.3770.24. I tried again with Linux support disabled in the settings, but the problem persists.

**Comment by emaxx-google** [comment]
Thanks for the bug report.
I've filed https://crbug.com/968111 to track the issue in the Chromium bugtracker.

**Comment by emaxx-google** [comment]
This was fixed on the Chrome side - the partial fix went into 75.0.3770.73, and a more complete one - into 76.0.3809.82.
