### ISSUE TITLE
Manifest.json Missing { "vendorId": 1839, "productId": 8704 }

### ISSUE THREAD

**Issue by Test18415** [GoogleChromeLabs/chromeos_smart_card_connector#739]
We have a reader that works in a chromebook, namely the acr122u. We can extract custom data from nfc cards via the chromeos_smart_card_connector (https://chrome.google.com/webstore/detail/smart-card-connector/khpfeaanjngmcnplbdlpegiifgpfgdco?hl=nl) app in combination with the library here provided, implemented in our custom chrome app. 

But we have trouble using it on chrome enterprise kiosk. It should detect the reader immideatly, but somehow it doesn't, it doesn't even burn the light on the reader. It works outside the chrome enterprise kiosk though.

We think this is because the vendor id product id is not in the manifest.json. { "vendorId": 1839, "productId": 8704 } is missing, are we correct?

**Comment by emaxx-google** [comment]
Hello, a few thoughts/questions:

1. When you're saying it works outside the chrome enterprise kiosk, do you mean that it works after clicking "add reader" in the Smart Card Connector's UI? In that case, indeed, changing the config would allow to skip this step.

2. Are you sure the `productId` you mentioned is a correct one? The CCID Driver's website mentions a different number: https://ccid.apdu.fr/ccid/readers/ACR122U.txt

3. You could try configuring the `WebUsbAllowDevicesForUrls` admin policy to allow your device to the Smart Card Connector. This solution, if it's workable, won't rely on us updating `manifest.json` (per https://crbug.com/1295084).

**Comment by Test18415** [comment]
1. Okay that is great, that is what we mean.
2. Yeah, maybe we have a new version, the ACR122U-A9 product id when we connect the smart card reader to a windows computer is 2200, the VID is 072F, which converted to hexidecimal is { "vendorId": 1839, "productId": 8704 }. 
Here is a search, it says ACR122U: https://www.the-sz.com/products/usbid/index.php?v=072F&p=2200&n=
3. Good! We will try that route, answer coming up

Thank you for the response!
