### ISSUE TITLE
getBackgroundPage error isn't caught

### ISSUE THREAD

**Issue by vapier** [GoogleChromeLabs/chromeos_smart_card_connector#755]
trying to convert Secure Shell to MV3 and i'm seeing a crash.  i'm using v1.3.9.3 here.
```
00:40:00.842 google-smart-card-client-library.js:80
[221005 00:40:00.83] [] Failure
Gc @ google-smart-card-client-library.js:80

00:40:00.848 nassh.html:1
Error handling response: Error: Failure
    at Mc (chrome-extension://algkcnfjnajfhgimadimbjhmpaeohhln/third_party/google-smart-card/google-smart-card-client-library.js:82:215)
    at chrome-extension://algkcnfjnajfhgimadimbjhmpaeohhln/third_party/google-smart-card/google-smart-card-client-library.js:80:1018

00:40:00.848 nassh.html:1
Unchecked runtime.lastError: You do not have a background page.
```

afaik, Chrome requires you to read `chrome.runtime.lastError` otherwise it throws an exception like this.
```
chrome.runtime.getBackgroundPage((bg) => {
  if (bg === undefined) {
    const error = chrome.runtime.lastError?.message;
    ...
    return;
  }
  ...
});
```

**Comment by emaxx-google** [comment]
@vapier Thanks for reporting this! Please let me know if there are further issues with ServiceWorkers (I've done a quick test on my side, but it was not comprehensive).

**Comment by vapier** [comment]
also verified 1.3.10.1 is OK.  i see it's marked as a prerelease ... how often normally before those go to proper releases ?  i don't want to roll a new version that isn't recommended.

**Comment by emaxx-google** [comment]
Expecting not more than in 2 weeks (I originally wanted to do it straight away, but got no blessing from QA - and this is still pending).
