### ISSUE TITLE
Fix clean for 'coverage' and 'asan_testing' toolchains

### ISSUE THREAD

**Issue by ViktoriiaKovalova** [GoogleChromeLabs/chromeos_smart_card_connector#948]
Because integration tests are included into certain clean targets for all toolchains, e.g. in `example_cpp_smart_card_client_app/build/Makefile`, `clean-all.sh` breaks when cleaning with toolchain=coverage and toolchain=asan_testing.

**Comment by emaxx-google** [comment]
Thanks for catching it. Now that I'm thinking about it, we should probably drop those test-specific references from nested makefiles like `example_cpp_smart_card_client_app/build/`. We're shifting towards the model in which developers should only trigger make in the root folder, and the root makefile already knows about all modalities.
